"""phase2-8 domains

Revision ID: 1107296303a7
Revises: 20260809_phase1_auth_profile
Create Date: 2026-08-09 18:15:12.047570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1107296303a7'
down_revision: Union[str, None] = '20260809_phase1_auth_profile'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_conversations_id'), 'coach_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_coach_conversations_user_id'), 'coach_conversations', ['user_id'], unique=False)
    op.create_table('coach_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=40), nullable=False),
    sa.Column('recommendation', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('remaining_calories', sa.Integer(), nullable=False),
    sa.Column('remaining_protein_g', sa.Integer(), nullable=False),
    sa.Column('uncertainty', sa.Boolean(), nullable=False),
    sa.Column('suggested_action', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_recommendations_id'), 'coach_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_coach_recommendations_user_id'), 'coach_recommendations', ['user_id'], unique=False)
    op.create_table('daily_steps_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_steps_user_date')
    )
    op.create_index(op.f('ix_daily_steps_entries_id'), 'daily_steps_entries', ['id'], unique=False)
    op.create_index(op.f('ix_daily_steps_entries_user_id'), 'daily_steps_entries', ['user_id'], unique=False)
    op.create_table('daily_water_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_water_user_date')
    )
    op.create_index(op.f('ix_daily_water_entries_id'), 'daily_water_entries', ['id'], unique=False)
    op.create_index(op.f('ix_daily_water_entries_user_id'), 'daily_water_entries', ['user_id'], unique=False)
    op.create_table('daily_weight_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_weight_user_date')
    )
    op.create_index(op.f('ix_daily_weight_entries_id'), 'daily_weight_entries', ['id'], unique=False)
    op.create_index(op.f('ix_daily_weight_entries_user_id'), 'daily_weight_entries', ['user_id'], unique=False)
    op.create_table('foods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serving_size_g', sa.Float(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    op.create_index(op.f('ix_foods_user_id'), 'foods', ['user_id'], unique=False)
    op.create_table('menu_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_images_id'), 'menu_images', ['id'], unique=False)
    op.create_index(op.f('ix_menu_images_user_id'), 'menu_images', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hydration_enabled', sa.Boolean(), nullable=False),
    sa.Column('protein_enabled', sa.Boolean(), nullable=False),
    sa.Column('meal_enabled', sa.Boolean(), nullable=False),
    sa.Column('end_of_day_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=False),
    sa.Column('quiet_hours_end', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('day_key', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_day_key'), 'notifications', ['day_key'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sleep_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wake_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_sleep_user_date')
    )
    op.create_index(op.f('ix_sleep_entries_id'), 'sleep_entries', ['id'], unique=False)
    op.create_index(op.f('ix_sleep_entries_user_id'), 'sleep_entries', ['user_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('coach_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['coach_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_messages_conversation_id'), 'coach_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_coach_messages_id'), 'coach_messages', ['id'], unique=False)
    op.create_table('food_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('food_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=40), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_entries_food_id'), 'food_entries', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_entries_id'), 'food_entries', ['id'], unique=False)
    op.create_index(op.f('ix_food_entries_user_id'), 'food_entries', ['user_id'], unique=False)
    op.create_table('menu_image_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('menu_image_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('estimated_calories', sa.Integer(), nullable=False),
    sa.Column('estimated_protein_g', sa.Integer(), nullable=False),
    sa.Column('estimated_carbs_g', sa.Integer(), nullable=False),
    sa.Column('estimated_fat_g', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_image_id'], ['menu_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_image_items_id'), 'menu_image_items', ['id'], unique=False)
    op.create_index(op.f('ix_menu_image_items_menu_image_id'), 'menu_image_items', ['menu_image_id'], unique=False)
    op.drop_constraint(op.f('nutrition_targets_user_id_key'), 'nutrition_targets', type_='unique')
    op.drop_index(op.f('ix_nutrition_targets_user_id'), table_name='nutrition_targets')
    op.create_index(op.f('ix_nutrition_targets_user_id'), 'nutrition_targets', ['user_id'], unique=True)
    op.drop_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', type_='unique')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_nutrition_targets_user_id'), table_name='nutrition_targets')
    op.create_index(op.f('ix_nutrition_targets_user_id'), 'nutrition_targets', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('nutrition_targets_user_id_key'), 'nutrition_targets', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_menu_image_items_menu_image_id'), table_name='menu_image_items')
    op.drop_index(op.f('ix_menu_image_items_id'), table_name='menu_image_items')
    op.drop_table('menu_image_items')
    op.drop_index(op.f('ix_food_entries_user_id'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_id'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_food_id'), table_name='food_entries')
    op.drop_table('food_entries')
    op.drop_index(op.f('ix_coach_messages_id'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_conversation_id'), table_name='coach_messages')
    op.drop_table('coach_messages')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_sleep_entries_user_id'), table_name='sleep_entries')
    op.drop_index(op.f('ix_sleep_entries_id'), table_name='sleep_entries')
    op.drop_table('sleep_entries')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_day_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_menu_images_user_id'), table_name='menu_images')
    op.drop_index(op.f('ix_menu_images_id'), table_name='menu_images')
    op.drop_table('menu_images')
    op.drop_index(op.f('ix_foods_user_id'), table_name='foods')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_daily_weight_entries_user_id'), table_name='daily_weight_entries')
    op.drop_index(op.f('ix_daily_weight_entries_id'), table_name='daily_weight_entries')
    op.drop_table('daily_weight_entries')
    op.drop_index(op.f('ix_daily_water_entries_user_id'), table_name='daily_water_entries')
    op.drop_index(op.f('ix_daily_water_entries_id'), table_name='daily_water_entries')
    op.drop_table('daily_water_entries')
    op.drop_index(op.f('ix_daily_steps_entries_user_id'), table_name='daily_steps_entries')
    op.drop_index(op.f('ix_daily_steps_entries_id'), table_name='daily_steps_entries')
    op.drop_table('daily_steps_entries')
    op.drop_index(op.f('ix_coach_recommendations_user_id'), table_name='coach_recommendations')
    op.drop_index(op.f('ix_coach_recommendations_id'), table_name='coach_recommendations')
    op.drop_table('coach_recommendations')
    op.drop_index(op.f('ix_coach_conversations_user_id'), table_name='coach_conversations')
    op.drop_index(op.f('ix_coach_conversations_id'), table_name='coach_conversations')
    op.drop_table('coach_conversations')
    # ### end Alembic commands ###
